FORMAT: 1A
HOST: https://apex5.revion.com/

# BEBOMS

BEBOMS is a set of REST APIs allowing consumers to create customers and orders.

# API

The API base URL is https://apex5.revion.com/ords/bebomsdev. To call any API endpoint (method) you must append the endpoint name and parameters to the API URL.

Note: The API accepts only JSON data format.

You will need to:

    Create an account in BEBOMS before you can use the API.

# API Status Codes

| Status Code               | Description                                                                                                               |
|---------------------------|---------------------------------------------------------------------------------------------------------------------------|
| 400 Bad Request           | The request was not in a correct form,                                                                                    |
| 403 Forbidden             | Method authentication failed                                                                                              |
| 404 Not found             | Endpoint does not exist                                                                                                   |
| 405 Not allowed           | The method used is not allowed (eg PUT, DELETE)                                                                           |
| 500 Internal Server Error | The object passed to the API could not be parsed or some unexpected error occurred in BEBOMS while processing API request |
| 503 Service Unavailable   | You reached API limit.  Try again after some time                                                                         |


## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }