FORMAT: 1A
HOST: https://apex5.revion.com

# BEBOMS

BEBOMS is a set of REST APIs allowing consumers to create customers and orders.

# API

The API base URL is https://apex5.revion.com/ords/beboms. To call any API endpoint (method) you must append the endpoint name and parameters to the API URL.

Note: The API accepts only JSON data format.

You will need to:

    Have an account created in BEBOMS before you can use the API.

# Authentication

To use the API you will need your BEBOMS Client ID and API Token. Contact admin@branaenterprises.com.com for details.

Your Client Id and API Token are equivalent to a login and password. They must be kept secret and not shared in any way.

Each request to the API must include these two values sent as HTTP headers:

| Header        | Description                                 |
|---------------|---------------------------------------------|
| Authorization | You must send your API token in this header |
| client_id     | You must send your client Id in this header |
    
# API Status Codes

| Status Code               | Description                                                                                                               |
|---------------------------|---------------------------------------------------------------------------------------------------------------------------|
| 400 Bad Request           | The request was not in a correct form,                                                                                    |
| 403 Forbidden             | Method authentication failed                                                                                              |
| 404 Not found             | Endpoint does not exist                                                                                                   |
| 405 Not allowed           | The method used is not allowed (eg PUT, DELETE)                                                                           |
| 500 Internal Server Error | The object passed to the API could not be parsed or some unexpected error occurred in BEBOMS while processing API request |
| 503 Service Unavailable   | You reached API limit.  Try again after some time                                                                         |

## Inventory [/ords/beboms/inventory/products/]

### Get Products [GET]
+ Request
    + Headers
    
            client_id: client_id
            Authorization: Bearer access_token

+ Response 200 (application/json)

        {
            "rc_Products": [
                {
                    "product_id": 11054,
                    "sku": "609239632886",
                    "product_name": "250-2",
                    "qty_on_hand": -12,
                    "product_avail": "Y",
                    "list_price": 0.9,
                    "upc_code": null,
                    "net_wt": null,
                    "product_description": "At My Age, TTYL Car Coaster"
                },
                {
                    "product_id": 11072,
                    "sku": "722537719179",
                    "product_name": "RH5-104",
                    "qty_on_hand": -4,
                    "product_avail": "Y",
                    "list_price": 7.5,
                    "upc_code": null,
                    "net_wt": null,
                    "product_description": "Live the Life you Love  Box Sign"
                }
            ]
        }

## Customer [/ords/beboms/customer/customer/]

### Get Customers [GET]
+ Request
    + Headers
    
            client_id: client_id
            Authorization: Bearer access_token

+ Response 200 (application/json)

        {
            "rc_Customers": [
                {
                    "customer_id": 30938,
                    "company_name": "Test Customer Active",
                    "cust_street_address1": "123 main street",
                    "cust_street_address2": null,
                    "cust_street_address3": null,
                    "cust_city": "Largo",
                    "cust_state": "IL",
                    "cust_postal_code": "33773",
                    "cust_province": null,
                    "country_code": "US",
                    "bill_phone": "123-123-1234",
                    "bill_email": null,
                    "ship_company_name": "Test Customer Active",
                    "ship_street_address1": "123 main street",
                    "ship_street_address2": null,
                    "ship_street_address3": null,
                    "ship_city": "Largo",
                    "ship_state": "IL",
                    "ship_postal_code": "33773",
                    "ship_province": null,
                    "ship_country_code": null,
                    "ship_phone": "123-123-1234",
                    "ship_email": null
                },
                {
                    "customer_id": 30919,
                    "company_name": "Test Company4",
                    "cust_street_address1": "cust street address1",
                    "cust_street_address2": "cust_street_address2",
                    "cust_street_address3": "cust_street_address3",
                    "cust_city": "cust_city",
                    "cust_state": "FL",
                    "cust_postal_code": "33773",
                    "cust_province": null,
                    "country_code": "US",
                    "bill_phone": "123-456-7890",
                    "bill_email": "test@test.com",
                    "ship_company_name": "Test Company4",
                    "ship_street_address1": "cust street address1",
                    "ship_street_address2": "cust_street_address2",
                    "ship_street_address3": "cust_street_address3",
                    "ship_city": "cust_city",
                    "ship_state": "FL",
                    "ship_postal_code": "33773",
                    "ship_province": null,
                    "ship_country_code": null,
                    "ship_phone": "123-456-7890",
                    "ship_email": "test2@test.com"
                }
            ]
        }

### Create a New Customer [POST]

You may create a new customer using this action. 

+ Request
    + Headers
    
            client_id: client_id
            Authorization: Bearer access_token
            
    + Body

            {
                "company_name": "Test Company4",
                "cust_first_name": "TestFirstName2",
                "cust_last_name": "TestLastName",
                "cust_street_address1": "cust street address1",
                "cust_street_address2": "cust_street_address2",
                "cust_street_address3": "cust_street_address3",
                "cust_city": "cust_city",
                "cust_state": "FL",
                "cust_province": "",
                "cust_postal_code": "33773",
                "bill_email": "test@test.com",
                "ship_email": "test2@test.com",
                "bill_phone": "123-456-7890",
                "ship_phone": "987-654-3210",
                "url": "",
                "tax_id":"",
                "same_ship_address": "Y",
                "ship_street_address1": "",
                "ship_street_address2": "",
                "ship_street_address3":"",
                "ship_city": "",
                "ship_state": "",
                "ship_province": "",
                "ship_postal_code": "",
                "ship_company_name": "",
                "account_number": "",
                "bill_company_name": "",
                "country_code": "US",
                "ship_country_code": "US"
            }

+ Response 201 (application/json)

    + Body

            {
               "customer_id": "30986"
            }
            
            
## Order [/ords/beboms/order/order/{order_id}]

+ Parameters
    + order_id (number) - 49659

### Get Order [GET]
+ Request
    + Headers
    
            client_id: client_id
            Authorization: Bearer access_token

+ Response 200 (application/json)

        {
            "rc_Order": [
                {
                    "customer_id": 20495,
                    "order_total": 111.37,
                    "order_timestamp": "2020-09-11T19:38:47Z",
                    "create_date": "2020-10-25T20:04:28Z",
                    "status": "NEW",
                    "shipping_cost": 0,
                    "notes": "Please pay by check",
                    "po_number": "SHTEST2",
                    "order_items": [
                        {
                            "order_item_id": 559819,
                            "product_id": 125,
                            "sku": "CRAN",
                            "unit_price": 49.5,
                            "quantity": 1
                        },
                        {
                            "order_item_id": 559820,
                            "product_id": 126,
                            "sku": "FRCLN",
                            "unit_price": 49.5,
                            "quantity": 1
                        },
                        {
                            "order_item_id": 559821,
                            "product_id": 127,
                            "sku": "RENEG",
                            "unit_price": 49.5,
                            "quantity": 1
                        }
                    ]
                }
            ]
        }

## Create Order [/ords/beboms/order/order/]

### Create a New Order[POST]

You may create a new order using this action. 

+ Request
    + Headers
    
            client_id: client_id
            Authorization: Bearer access_token
            
    + Body

            {
                "Order": [
                    {
                        "customer_id": 20495,
                        "order_total": 111.37,
                        "order_timestamp": "2021-01-20T20:04:28Z",
                        "create_date": "2021-01-20T20:04:28Z",
                        "paid_date": "2021-01-20T20:04:28Z",
                        "status": "NEW",
                        "shipping_cost": 0,
                        "notes": "Please pay by check",
                        "po_number": "SHTEST2",
                        "order_source": "FAIRE",
                        "order_items": [
                            {
                                "product_id": 125,
                                "sku": "CRAN",
                                "unit_price": 49.5,
                                "quantity": 1
                            },
                            {
                                "product_id": 660,
                                "sku": "SWTDR",
                                "unit_price": 49.5,
                                "quantity": 1
                            },
                            {
                                "product_id": 740,
                                "sku": "TBLTNT",
                                "unit_price": 0,
                                "quantity": 1
                            }
                        ]
                    }
                ]
            }

+ Response 201 (application/json)

    + Body

            {
                "rc_Order": [
                    {
                        "order_id": 49667,
                        "customer_id": 20495,
                        "po_number": "SHTEST2",
                        "order_total": 111.37,
                        "shipping_cost": 0,
                        "order_source": "FAIRE",
                        "notes": "Please pay by check",
                        "order_items": [
                            {
                                "order_item_id": 559928,
                                "product_id": 125,
                                "sku": "CRAN",
                                "quantity": 1
                            },
                            {
                                "order_item_id": 559929,
                                "product_id": 660,
                                "sku": "SWTDR",
                                "quantity": 1
                            },
                            {
                                "order_item_id": 559930,
                                "product_id": 740,
                                "sku": "TBLTNT",
                                "quantity": 1
                            }
                        ]
                    }
                ]
            }

## Add Order Items [/ords/beboms/order_items/order_items/{order_id}]

+ Parameters
    + order_id (number) - 49659

### Add Order Items[POST]

You may add items to an order using this action. 

+ Request
    + Headers
    
            client_id: client_id
            Authorization: Bearer access_token
            
    + Body

            {
                "order_items": [
                    {
                        "product_id": 125,
                        "sku": "CRAN",
                        "unit_price": 49.5,
                        "quantity": 1
                    },
                    {
                        "product_id": 3200,
                        "sku": "DARL",
                        "unit_price": 49.5,
                        "quantity": 1
                    },
                    {
                        "product_id": 7328,
                        "sku": "20BAGS",
                        "unit_price": 0,
                        "quantity": 1
                    }
                ]
            }

+ Response 201 (application/json)

    + Body

            {
                "rc_OrderItems": [
                    {
                        "order_item_id": 559899,
                        "product_id": 125,
                        "quantity": 1,
                        "sku": "CRAN",
                        "unit_price": 49.5
                    },
                    {
                        "order_item_id": 559911,
                        "product_id": 3200,
                        "quantity": 1,
                        "sku": "DARL",
                        "unit_price": 49.5
                    },
                    {
                        "order_item_id": 559912,
                        "product_id": 7328,
                        "quantity": 1,
                        "sku": "20BAGS",
                        "unit_price": 0
                    }
                ]
            }
            
## Tracking [/ords/beboms/tracking/orders/{from_date}]

You may get order tracking information with this action. 

+ Parameters
    + from_date (string) - 2021-01-20T20:04:28Z

### Get Orders [GET]
+ Request
    + Headers
    
            client_id: client_id
            Authorization: Bearer access_token

+ Response 200 (application/json)

        {
            "rc_Orders": [
                {
                    "order_source": "POSTMAN",
                    "order_id": 49661,
                    "po_number": "SHTEST2",
                    "tracking_number": "782998071361",
                    "shipping_cost": 0
                },
                {
                    "order_source": "FAIRE",
                    "order_id": 49672,
                    "po_number": "BO_CT22BPCVQA",
                    "tracking_number": "782998071370",
                    "shipping_cost": 0
                },
                {
                    "order_source": "FAIRE",
                    "order_id": 49673,
                    "po_number": "BO_9I9DVUR1GC",
                    "tracking_number": "782998071371",
                    "shipping_cost": 0
                },
                {
                    "order_source": "FAIRE",
                    "order_id": 49674,
                    "po_number": "BO_H1V2RYLE7A",
                    "tracking_number": "782998071372",
                    "shipping_cost": 0
                },
                {
                    "order_source": "FAIRE",
                    "order_id": 49675,
                    "po_number": "BO_5M29FLOGPC",
                    "tracking_number": "782998071373",
                    "shipping_cost": 0
                },
                {
                    "order_source": "FAIRE",
                    "order_id": 49677,
                    "po_number": "BO_7UKX2P1YZ6",
                    "tracking_number": "782998071374",
                    "shipping_cost": 0
                },
                {
                    "order_source": "POSTMAN",
                    "order_id": 49652,
                    "po_number": "SHTEST2",
                    "tracking_number": "782998071375",
                    "shipping_cost": 0
                }
            ]
        }